### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SamuelCarroll**

### CODE REVIEW

**Comment by Zalgo2462** [comment]
After the latest pull request, the error message given was removed and replaced:
```
converter_1  | ERRO[0840] input must contain valid start and end timestamps.
converter_1  | 
converter_1  | If this problem persists, please report this problem at
converter_1  | support@activecountermeasures.com. If your device supports
converter_1  | alternative versions of Netflow, you may resolve this issue by
converter_1  | disabling IPFIX and enabling Netflow version 5 or 9.  inputMap="map[@version:1 host:10.55.182.1 @timestamp:\"2018-12-05T01:13:18.000Z\" _id:ObjectIdHex(\"5c0726344fa47aab47000028\") netflow:map[sourceIPv4Address:10.55.100.110 sourceTransportPort:58905 version:10 octetDeltaCount:62 flowEndSysUpTime:8939148 destinationIPv4Address:10.55.200.10 protocolIdentifier:17 tcpControlBits:0 flowStartSysUpTime:8939147 egressInterface:1 ipVersion:4 packetDeltaCount:1 destinationTransportPort:53 vlanId:0 icmpTypeCodeIPv4:0 ipClassOfService:0 ingressInterface:1]]" stacktrace="[flow_deserializer.go:212 flow_deserializer.go:667 id_bulk_buffer.go:101 reader.go:61 reader.go:45 asm_amd64.s:2361]"
converter_1  | ERRO[0840] input must contain valid start and end timestamps.
converter_1  | 
converter_1  | If this problem persists, please report this problem at
converter_1  | support@activecountermeasures.com. If your device supports
converter_1  | alternative versions of Netflow, you may resolve this issue by
converter_1  | disabling IPFIX and enabling Netflow version 5 or 9.  inputMap="map[_id:ObjectIdHex(\"5c0726344fa47aab47000029\") netflow:map[ipClassOfService:0 ipVersion:4 version:10 vlanId:0 icmpTypeCodeIPv4:0 destinationIPv4Address:10.55.200.11 packetDeltaCount:1 destinationTransportPort:53 flowEndSysUpTime:8939355 flowStartSysUpTime:8939235 ingressInterface:1 sourceTransportPort:59453 protocolIdentifier:17 tcpControlBits:0 sourceIPv4Address:10.55.100.111 octetDeltaCount:75 egressInterface:1] @version:1 host:10.55.182.1 @timestamp:\"2018-12-05T01:13:18.000Z\"]" stacktrace="[flow_deserializer.go:212 flow_deserializer.go:667 id_bulk_buffer.go:101 reader.go:61 reader.go:45 asm_amd64.s:2361]"
```

This is a capture from the error log using PFSense + Softflowd before the systemInitTimeMilliseconds record comes in.

**Comment by SamuelCarroll** [comment]
Yep, but I did a bad and didn't get that change incorporated into RC1. It was decided that it would be easier to throw in a notice about it than to vet another release candidate

**Comment by SamuelCarroll** [comment]
Let me do a once over the README, I feel like I'm forgetting to add something, and once I have that confirmed I'll add the updated README to RC1

**Comment by Zalgo2462** [comment]
One thing I ran into that was frustrating that we might want to note.
If you want to bind to multiple ip addresses in the mongod config, you have to enter them as "1.1.1.1,2.2.2.2" i.e. with a commas between the ip addresses and WITHOUT spaces. Otherwise Mongo will crash. If this doesn't seem necessary to you, then I think we're good to go.

**Pull request merged**
